### ISSUE TITLE
Good job

### ISSUE THREAD

**Issue by ysBach** [pleiades23/Ple_AO#3]
Please rename a file (e.g., ``test.dat``) to something else via

```
$ git mv test.dat test1.dat
$ git add test1.dat
$ git commit -m "blahblah. Fixes #<this issue number>``
$ git push
```

**Comment by pleiades23** [comment]
Thank you for feedback. 
I’m sorry to be late for fixing and replying.

Jangho Bae


보낸 사람: Yoonsoo P. Bach
보낸 날짜: 2020년 4월 23일 목요일 오후 4:20
받는 사람: pleiades23/Ple_AO
참조: Subscribed
제목: [pleiades23/Ple_AO] Good job (#3)

Please rename a file (e.g., test.dat) to something else via
$ git mv test.dat test1.dat
$ git add test1.dat
$ git commit -m "blahblah. Fixes #<this issue number>``
$ git push
